apiVersion: v1
kind: Service
metadata:
  labels:
    system: {{ .Values.system }}
    component: {{ .Values.component }}
  name: {{ .Values.component }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    system: {{ .Values.system }}
    component: {{ .Values.component }}