kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.component }}-pipeline-registry-access
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.system }}-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
