apiVersion: v1
kind: Service
metadata:
  labels:
    system: {{ .Values.system }}
    component: {{ .Values.component }}
    'backstage.io/kubernetes-id': {{ .Values.component }}
  name: {{ .Values.component }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    system: {{ .Values.system }}
    component: {{ .Values.component }}