apiVersion: v1
kind: Service
metadata:
  labels:
    system: {{ .Values.system }}
    component: {{ .Values.component }}
  name: {{ .Values.component }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPorts.service }}
      protocol: TCP
      targetPort: {{ .Values.containerPorts.service }}
    - port: {{ .Values.containerPorts.management }}
      protocol: TCP
      targetPort: {{ .Values.containerPorts.management }}
  selector:
    system: {{ .Values.system }}
    component: {{ .Values.component }}