system: default-application
component: default-service
environment: dev

image:
  registry: image-registry.openshift-image-registry.svc:5000
  tag: latest

replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
